### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Vglib** [skuep/GDS3D#2]
After Installing all packets GDS3D need,  made the following sentence from a example I found:

/GDS3D -p onc18.txt -i Prop2_v1.gds
I got:
[root@---]# Program received signal SIGSEGV, Segmentation fault.
Program received signal SIGSEGV, Segmentation fault.
0x000000000040a2da in Wm_X11::main(int, char**) ()

Debugging with gdb:

Program received signal SIGSEGV, Segmentation fault.
0x000000000040a2da in Wm_X11::main(int, char**) ()
....

(gdb) bt
#0  0x000000000040a2da in Wm_X11::main(int, char**) ()
#1  0x000000000040a77e in main ()

Please, could you give any help?

Thanks.

**Comment by horror-vacui** [comment]
I also had a segmentation fault on a 375kByte gds.  
I use a Xubuntu 16.04 LTS machine.

```
~/Downloads/GDS3D_1.8/linux/GDS3D -p ~/Downloads/GDS3D_1.8/techfiles/GDS3D_22FDX_st11.txt -i ./01_dut_open.gds

==============================================================================
GDS3D v1.8, Copyright (C) 2013 IC-Design Group, University of Twente
Created by Jasper Velner and Michiel Soer, http://icd.el.utwente.nl
Based on code by Roger Light, http://atchoo.org/gds2pov/
==============================================================================

Opened process file "/home/tibenszky/Downloads/GDS3D_1.8/techfiles/GDS3D_22FDX_st11.txt"

Opening GDS file "./01_dut_open.gds"..

Segmentation fault (core dumped)
```

**Comment by horror-vacui** [comment]
The code in https://github.com/trilomix/GDS3D has not given segmentation for a layout, where this repo did. That other one seem to be active as well.
